### PR TITLE
purge old external cirrus.lib package

### PR DESCRIPTION
**Pull request by ircwaves**
With the archival of `cirrus-lib` it seems reasonable time for the external cirrus-lib package to go now, agreed?

### CODE REVIEW

**Comment by ircwaves** [comment]
@jkeifer -- I don't know if this change is too soon or not, but after bonking the "re-run jobs" button twice (only one job seems to be able to upload coverage at a time), the tests passed w/ the change in coverage likely due to winning at code-golf.

**Comment by philvarner** [comment]
@jkeifer thoughts about merging this?

**Comment by jkeifer** [comment]
I'm good with this, the only thing I'd call out is adding a clear "Breaking Changes" section to the `CHANGELOG.md` (as has been done in the past for breaking changes) with the instruction that any users relying on the automatic packaging of `cirrus.lib` into lambdas will need to explicitly add `cirrus.lib` to those function requirements (and that `cirrus.lib` is no longer maintained and that we recommend migrating to `stac-task`).

**Comment by philvarner** [comment]
> I'm good with this, the only thing I'd call out is adding a clear "Breaking Changes" section to the `CHANGELOG.md` (as has been done in the past for breaking changes) with the instruction that any users relying on the automatic packaging of `cirrus.lib` into lambdas will need to explicitly add `cirrus.lib` to those function requirements (and that `cirrus.lib` is no longer maintained and that we recommend migrating to `stac-task`).

I'll make that change

**Review by philvarner — APPROVED** [review]

**Pull request merged**
